# Generated by Django 4.2 on 2023-05-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bootstrapmade", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="menulist", name="dish_id",),
        migrations.RemoveField(model_name="menulist", name="menu_category_id",),
        migrations.AddField(
            model_name="menulist",
            name="dish",
            field=models.ForeignKey(
                # default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="bootstrapmade.dishes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menulist",
            name="menu_category",
            field=models.ForeignKey(
                # default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="bootstrapmade.menucategory",
            ),
            preserve_default=False,
        ),
    ]
