# Generated by Django 4.2 on 2023-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootstrapmade", "0002_remove_menulist_dish_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulist",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
